Sprint 3
antonabaltusov/middle.messenger.praktikum.yandex pull request #4
Opened 2022-12-04 14:15 UTC by antonabaltusov

2022-12-05 03:05 UTC, maks88sgt requested changes
Привет! Отличная работа. У тебя хорошо получилось структурировать проект, здорово, что вся работа с апи сделана через try/catch. Порадовало использование TS, нигде не встретил any и отключение TS что довольно редко на проектах. Перед тем как идти дальше предлагаю поправить минорные вещи, которые немного портят твой проект:
1. Добавить в package.json скрипт для запуска eslint и исправить все ошибки, которые он найдет. Их довольно много.
2. Убрать закомментированный код и пустые блоки finally.
3. Переписать сервисы и апи на классы (не совсем обязательно). Привести в порядок именования, чтобы везде было однообразно (обязательно).

2022-12-05 03:05 UTC, maks88sgt commented on src/api/base-api.ts
> +export const baseUrl = 'https://ya-praktikum.tech/api/v2/';
Довольно распространенная практика использовать верхний регистр для констант, это отличает их от других переменных в коде. https://learn.javascript.ru/variables#konstanty-v-verhnem-registre

2022-12-05 03:05 UTC, maks88sgt commented on src/api/login-api.ts
> +//type LoginResponseData = UserDTO | APIError;
Закомментированный код лучше сразу удалять, он не несет никакой пользы, а только захламляет проект.

2022-12-05 03:05 UTC, maks88sgt commented on src/blocks/FormPassword/FormPassword.ts
> +      } finally {
Если в этом блоке не предусмотрено никаких действий, лучше удалить его.

2022-12-05 03:05 UTC, maks88sgt commented on src/services/chatService.ts
> +export const ChatService = {
Обычно с большой буквы принято именовать классы. А так получается у тебя где-то используются разные именования в одном проекте, что довольно нехорошо. В целом я за то чтобы переписать сервисы и апи на классы и использовать их, тогда и именование будет нужно делать с большой буквы.

2022-12-05 03:05 UTC, maks88sgt commented on src/services/chatService.ts
> +      `wss://ya-praktikum.tech/ws/chats/${state.user?.id}/${chatId}/${token}`
URL для вебсокетов тоже можно вынести в переменную

2022-12-05 03:05 UTC, maks88sgt commented on src/services/Socket.ts
> +    this.socket = ChatService.createSocket();
ChatService.createSocket принимает два аргумента, а здесь не передается ни одного.

2022-12-05 06:55 UTC, antonabaltusov commented on src/services/chatService.ts
> +export const ChatService = {
переименовал

2022-12-05 06:56 UTC, antonabaltusov commented on src/services/Socket.ts
> +    this.socket = ChatService.createSocket();
удалил файл

2022-12-07 03:13 UTC, maks88sgt approved these changes
Привет. Работу принял. Успехов на курсе!

2022-12-11 10:52 UTC, merged